apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: {{ .Values.namespace }}
  labels:
      release: "{{ .Release.Name }}_{{ .Release.Revision }}"
spec:
  containers:
  - name: test-container
    image: nginx:1.24
    env:
    - name: DB_URL
      value: {{ .Values.db_url }}
